In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,3,4,"jesse"]
a

[1, 2, 3, 4, 'jesse']

In [5]:
np.array(a)

array(['1', '2', '3', '4', 'jesse'], dtype='<U21')

In [6]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr=np.ones([2,2])
arr

array([[1., 1.],
       [1., 1.]])

In [15]:
arr=np.linspace(0,1,100) #(start, end, how many numbers you want in the middle) Each number has the same spacing
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
np.random.rand(10) #random generation normalization

array([0.19194286, 0.97406623, 0.92874892, 0.71979377, 0.91135167,
       0.81490824, 0.29545879, 0.71635837, 0.01488397, 0.46408952])

In [18]:
np.random.randn(10) #standardization -1 to 3

array([ 1.21934508,  0.95455331, -0.97346407,  0.6854126 , -0.10821372,
        0.4077101 ,  1.67653049,  0.56449526,  0.086396  , -2.17629118])

In [ ]:
np.random.randint(10,20,10) #(start point, end point, number of random numbers needed)

array([12, 10, 13, 18, 10, 18, 10, 13, 15, 18], dtype=int32)

In [33]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(12)

In [23]:
arr.sum()

np.int64(78)

In [24]:
np.sum(arr, axis=1)

array([10, 26, 42])

In [26]:
arr.mean()

np.float64(6.5)

In [28]:
arr.argmax()

np.int64(11)

In [34]:
#Array indexing and slicing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
print(arr[5])
print(arr[2])
print(arr[9])

16
13
20


In [41]:
array_slice= arr[::2] #[start:end:steps]
print(array_slice)

[11 13 15 17 19]


In [42]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[1,0] #[rows,columns]

np.int64(6)

In [46]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [53]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [55]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [58]:
arr1=np.arange(1,6)
arr2=np.arange(6,11)
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [65]:
#operations
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)
print(arr1 // arr2)
print(arr1 ** arr2)

#broadcasting
print(arr1 + 10)
print(arr2 + 10)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
[0 0 0 0 0]
[      1     128    6561  262144 9765625]
[11 12 13 14 15]
[16 17 18 19 20]


In [ ]:
#matrics operations
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

array([[5, 6],
       [7, 8]])

In [70]:
a

array([[1, 2],
       [3, 4]])

In [71]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a @ b #multiplication of 2d arrays

array([[19, 22],
       [43, 50]])

In [75]:
a.T #transpose

array([[1, 3],
       [2, 4]])

In [77]:
a = np.arange(1,6)
b = np.arange(6,11)

In [78]:
a

array([1, 2, 3, 4, 5])

In [79]:
b

array([ 6,  7,  8,  9, 10])

In [ ]:
np.vstack((a,b)) #vertical stackking

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b)) #horizontal stacking 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
np.column_stack((a,b)) #horizontal stacking 2D

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [91]:
#Splitting
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [94]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]